### PR TITLE
Strong naming Nodify

### PR DESCRIPTION
**Pull request by labiej**
### 📝 Description of the Change

Following the Microsoft recommendation to [strong name open-source libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries) this PR adds strong name signing. For more details see conversation #14 

A key is included, both a public-only key which can be used for delay signing.
I'm not entirely sure the public key is required. 

I have experienced the following;

* MyAssembly.dll needs to be tested, it is signed using MyKey.pfx  (target = .Net standard)
* MyAssembly.Test.dll is an assembly targeting .Net Core
* Some internal implementation details would benefit from testing so define InternalsVisibleTo
* MyAssembly.Test.dll needs to be signed but .Net Core does not support the PFX format

I resolved this by creating MyKey.public.snk and enabling delay signing.

I haven't tested whether this is still required in this case.

### 🐛 Possible Drawbacks

Changing the strong name key after the initial release of a signed package can potentially result in a breaking change.

### CODE REVIEW

**Comment by miroiu** [comment]
Hi, 
I played a bit with the signing and I think it's fine to disable delay signing for now unless I'm missing something.
Thanks for the PR!

Also please check out this PR before merging: https://github.com/labiej/nodify/pull/1

**Comment by labiej** [comment]
I've merged your PR so everything should be in order now.

**Comment by miroiu** [comment]
> Would it be useful to add a verification step in the build pipelines?

Yes, it would be useful, but I'm not sure how to do that. Running `sn.exe` may not work without specifying the full path to the executable. And also the output of this command is a string saying whether the .dll is valid or not which needs to be parsed in order to decide if the action should fail. At least this is my understading.

Do you think it's possible without creating a custom javascript action?

**Review by miroiu — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
